apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-frontend.fullname" . }}-config
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.nextPublicApiUrl | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  NEXT_PUBLIC_ENABLE_ANALYTICS: {{ .Values.config.nextPublicEnableAnalytics | quote }}
  NEXT_PUBLIC_LOG_LEVEL: {{ .Values.config.nextPublicLogLevel | quote }}
